version: "3.9"
services:
    flyway:
        image: redgate/flyway:9.16
        command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
        volumes:
          - ./migrations/sql:/flyway/sql
          - ./migrations/flyway.config:/flyway/conf/flyway.config
        depends_on:
          - postgres
    postgres:
        image: postgres:14.7
        restart: always
        ports:
           - "5432:5432"
        environment:
           - POSTGRES_USER=admin
           - POSTGRES_PASSWORD=admin
           - POSTGRES_DB=music_db
    music_service:
        build: music_service
        ports:
            - "5000:5000"
        depends_on:
            - flyway
        env_file:
            - .env
