name: fastapi-github-actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout docker-compose Docker image
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          services: |
            flyway
            postgres
            minio
            minio_bucket
            prediction_service
            ingestion_service
      - name: Build the Docker image
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Lint with flake8
        run: |
            pip install flake8
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
            pip install pytest

